# Generated by Django 2.0.1 on 2018-01-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180114_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='r_answer',
        ),
        migrations.RemoveField(
            model_name='results',
            name='r_question',
        ),
        migrations.AddField(
            model_name='results',
            name='a1',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='results',
            name='a2',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='results',
            name='a3',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='results',
            name='a4',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='results',
            name='q1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='results',
            name='q2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='results',
            name='q3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='results',
            name='q4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mcq_quiz',
            name='option3',
            field=models.CharField(blank='True', max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='mcq_quiz',
            name='option4',
            field=models.CharField(blank='True', max_length=20, null='True'),
        ),
    ]
