# Generated by Django 2.0.1 on 2018-01-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180115_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='results',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='results',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='results',
            name='q4',
        ),
    ]
