# Generated by Django 2.0.1 on 2018-01-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180115_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='True_False',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfquestion', models.CharField(max_length=500)),
                ('tfoption1', models.CharField(blank='True', max_length=20, null='True')),
                ('tfoption2', models.CharField(blank='True', max_length=20, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='txt_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtquestion', models.CharField(max_length=500)),
                ('txtoption1', models.CharField(blank='True', max_length=20, null='True')),
            ],
        ),
        migrations.AddField(
            model_name='results',
            name='a10',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='results',
            name='a5',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='results',
            name='a6',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='results',
            name='a7',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='results',
            name='a8',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AddField(
            model_name='results',
            name='a9',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
    ]
