# Generated by Django 2.0.1 on 2018-01-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180115_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_quiz',
            name='mq_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='true_false',
            name='tq_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='txt_question',
            name='txtq_no',
            field=models.IntegerField(default=1),
        ),
    ]
