# Generated by Django 2.0.1 on 2018-01-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180115_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_quiz',
            name='mq_no',
        ),
        migrations.RemoveField(
            model_name='true_false',
            name='tq_no',
        ),
        migrations.RemoveField(
            model_name='txt_question',
            name='txtq_no',
        ),
    ]
