# Generated by Django 2.0.1 on 2018-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180115_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_quiz',
            name='mq_no',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='true_false',
            name='tq_no',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='txt_question',
            name='txtq_no',
            field=models.CharField(default='', max_length=5),
        ),
    ]
